name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Image Produk
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build image Grav (front-end website)
      - name: Build image Grav
        uses: docker/build-push-action@v6
        with:
          context: .
          file: grav/Dockerfile
          push: false
          tags: perpus-grav:ci

      # Build image SLiMS (OPAC)
      - name: Build image SLiMS
        uses: docker/build-push-action@v6
        with:
          context: ./slims
          file: slims/Dockerfile
          push: false
          tags: perpus-slims:ci
