name: release

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ghcr.io/mfa-labs/perpustakaan-sekolah

jobs:
  build-and-push:
    name: Build & Push Image Produk
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login ke GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- Image Grav (front-end) ----------
      - name: Build & push image Grav
        uses: docker/build-push-action@v6
        with:
          context: .
          file: grav/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ env.IMAGE_BASE }}-grav:${{ github.ref_name }}
            ${{ env.IMAGE_BASE }}-grav:latest

      # ---------- Image SLiMS (OPAC) ----------
      - name: Build & push image SLiMS
        uses: docker/build-push-action@v6
        with:
          context: ./slims
          file: slims/Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ env.IMAGE_BASE }}-slims:${{ github.ref_name }}
            ${{ env.IMAGE_BASE }}-slims:latest
